apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app

  template:
    metadata:
      labels:
        app : demo-app
    spec:
      containers:
        - name: demo-app
          image: nikhilkothale17/my_python1
